### ISSUE TITLE
where are atomotos running?

### ISSUE THREAD

**Issue by Backendeng** [DripMicro/Atomotos_Contract#1]
Hi, 
Atomotos contract is very clearly and simple.
So, How can I deploy ?

**Comment by Backendeng** [comment]
Thank you.
so Can I deploy atomotos on bsc testnet?

**Comment by DripMicro** [comment]
ofc, you can deploy and test.

**Comment by Backendeng** [comment]
Ok,  got it. 
I will wait your update readme.
thank you.

**Comment by DripMicro** [comment]
I will update soon.
my pleasure
